Add index.html when creating directories in the filesystem
wp-media/imagify-plugin pull request #513
Opened 2020-09-02 18:53 UTC by iCaspar

Adding index files to directories we create in the filesystem to short-circuit public access to contents on servers that allow indexes.
- [ ] Create indexes in new directories as they are created.
- [ ] Run a directory scan of previously created imagify directories on update and add index files where missing.

2020-09-03 14:46 UTC, iCaspar commented
On the "Validate with NextGEN" item in the OP, we do not create separate backup directories for images uploaded into NextGEN galleries. Rather, backups are stored in directories already created by NextGEN alongside the optimized ones. Since we don't create those, we're going to leave them for NextGen to manage.

2020-09-03 15:25 UTC, iCaspar commented
@wp-media/qa @Davidacu This is ready for QA, Round 1.

2020-09-03 23:29 UTC, Davidacu reviewed
- Please find all scenarios tested under the test execution results file attached bellow
- The failure is unrelated to the changes, I already asked the team for more information.
- There is an index.php file being created under `/wp-content/uploads/` directory, it was fixed before but now it seems to be added back, could you please check @iCaspar 
[testrail-report-26.pdf](https://github.com/wp-media/imagify-plugin/files/5171856/testrail-report-26.pdf)

2020-09-04 17:29 UTC, Davidacu approved these changes
- All issues have been fixed.
- All cases have passed, please find the test result attached.
[testrail-report-27.pdf](https://github.com/wp-media/imagify-plugin/files/5176183/testrail-report-27.pdf)

2020-09-09 13:12 UTC, iCaspar commented
Unit and integration tests have been added here, but will require additional coverage in future releases. Because of the old architecture, adding further unit/integration coverage at this point will require major refactoring, too extensive to include in a minor release.
@hellofromtonya , This has passed QA is ready for code review.

2020-09-09 15:18 UTC, hellofromtonya requested changes

2020-09-09 15:18 UTC, hellofromtonya commented on inc/classes/class-imagify-custom-folders.php
> +				}
Apply `trailingslashit( $path )` before this block to do it once instead of 3x.

2020-09-09 15:18 UTC, hellofromtonya commented on imagify.php
> + * Version: 1.9.11
Please add the following header fields:

- Requires at least: The lowest WordPress version that the plugin will work on.
- Requires PHP: The minimum required PHP version.

[See WordPress Plugin manual for more info](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/#header-fields).

2020-09-09 15:34 UTC, hellofromtonya approved these changes

2020-09-09 15:38 UTC, merged