Use new promotion api data to specify applied plans in banner
wp-media/imagify-plugin pull request #555
Opened 2021-04-07 16:16 UTC by iCaspar

This is to allow the promotions banner in the pricing modal window to use data from the new api response rather than hard-coding "all" the plans into the banner's text during active promotions.

2 changes here:
- The view file is revised to insert a new span for the plan name(s) being promoted.
- The Javascript now parses the new `applied_to` information and uses it to populate the new span within the view.

2021-04-07 16:20 UTC, iCaspar commented
@wp-media/qa Ready for QA.
Acceptance criteria:
The pricing promotions banner should now display, depending on the active promotion:
(A) percentage off on all subscriptions
(B) percentage off on <<plan_name>> subscriptions
(C) percentage off on <<comma separated list of names>> subscriptions

2021-04-07 16:44 UTC, piotrbak commented
@iCaspar Do we have any environment where I could switch between the plans?

2021-04-07 16:53 UTC, Tabrisrp requested changes

2021-04-07 16:53 UTC, Tabrisrp commented on views/part-discount-banner.php
> +			__( '%s OFF on %s subscriptions', 'imagify' ),
```suggestion
			__( '%1$s OFF on %2$s subscriptions', 'imagify' ),
```

Little improvement to always match the placeholders with the arguments order

2021-04-07 17:39 UTC, Tabrisrp approved these changes

2021-04-08 15:14 UTC, Tabrisrp approved these changes

2021-04-08 15:26 UTC, piotrbak approved these changes

2021-04-08 15:53 UTC, merged