replace deprecated jquery functions
wp-media/imagify-plugin pull request #575
Opened 2021-07-06 06:00 UTC by mostafa-hisham

replace deprecated jquery functions

2021-07-08 17:57 UTC, iCaspar approved these changes

2021-07-08 17:58 UTC, iCaspar commented
Ready for @wp-media/qa 

Should make us free of quary deprecation notices!

2021-07-09 12:00 UTC, piotrbak requested changes
@iCaspar @mostafa-hisham There are still some:

`JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: disabled` in the `bulk.js` file:
`$( '#imagify-bulk-action' ).removeAttr( 'disabled' );`

`JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties: disabled` in the `options.js` file:
`$button.removeAttr( 'disabled' ).next( 'img' ).attr( 'aria-hidden', 'true' );`

2021-07-09 16:23 UTC, piotrbak approved these changes
We're good to go here!

2021-07-13 10:50 UTC, merged