Fix 495 Webp compatibility with WooCommerce variable product images
wp-media/imagify-plugin pull request #587
Opened 2021-07-07 21:02 UTC by iCaspar

Closes #495 

This is similar to what was groomed, but the method for invoking the filters is in a new compatibility class, and the filters themselves are more careful to guard against inadvertently removing other classes or adding/overwriting classes to other images on the page than the proof-of-concept code given.

2021-07-08 04:55 UTC, mostafa-hisham requested changes
php cs generated some errors for this class

- Filenames should be all lowercase with hyphens as word separators. Expected woocommerce.php, but found WooCommerce.php.
- Class file names should be based on the class name with "class-"
- Missing doc comment for functions and the class
- Visibility (Access Modifiers) must be declared on methods

2021-07-08 12:34 UTC, Tabrisrp requested changes
Missing docblocks everywhere, but validated the logic

2021-07-08 12:34 UTC, Tabrisrp commented on inc/3rd-party/WooCommerce/WooCommerce.php
> +$imagify_woocommerce_compat->init();
```suggestion
( new WooCommerce() )->init();
```

2021-07-08 12:34 UTC, Tabrisrp commented on inc/3rd-party/WooCommerce/WooCommerce.php
> +	function maybe_add_wp_post_image_class_on_picture_internal_tags( $attributes, $image ) {
```suggestion
	public function maybe_add_wp_post_image_class_on_picture_internal_tags( $attributes, $image ) {
```

2021-07-08 12:34 UTC, Tabrisrp commented on inc/3rd-party/WooCommerce/WooCommerce.php
> +	function remove_wp_post_image_class( $attributes, $image ) {
```suggestion
	public function remove_wp_post_image_class( $attributes, $image ) {
```

2021-07-08 12:40 UTC, iCaspar commented
Indeed, phpcs will not be happy with this yet.

Most of the rest of the plugin is using static/singleton type classes (a common WP plugin practice).
However, instead of using that pattern, I've put this in as a class and (another common WP plugin practice) created an instance and initialized it from within the included class file.

The other alternative I considered was folding these methods into the Webp/Picture/Display class -- but that does not properly separate concerns.

Per @Tabrisrp this will do until we have a chance to re-architect more thoroughly. I'll fix to conform to the naming conventions, etc.

2021-07-08 17:37 UTC, iCaspar commented
@wp-media/php @wp-media/qa Ready for recheck and QA.

2021-07-08 18:36 UTC, Tabrisrp approved these changes

2021-07-08 22:31 UTC, piotrbak commented
@iCaspar Could you tell me what is exactly going to happen in this PR? Are we going to add `wp-post-image` class to the images?

2021-07-09 17:21 UTC, iCaspar commented
So, on this one, WooCommerce is targeting images with `wp-post-image` class in the script that enables swapping out product images when the visitor selects different product variations from the drop-down on variable products selection. BUT the library does not support picture tags. To help them target the images for swap, we need to (1) remove `wp-post-image` class from the `<picture>` tag, and (2) add the `wp-post-image` class to all the `<source>` and `<img>` tags inside the `<picture>` tag.

In HTML inspector we should see:
Before:
```
<picture class="wp-post-image"...>
   <source src="path/to/image.webp"....>
   <img src="path/to/image.jpg"...>
</picture>
```
After:
```
<picture ...> // no class or class without wp-post-image included
   <source class="wp-post-image" src="path/to/image.webp"....>
   <img class="wp-post-image" src="path/to/image.jpg"...>
</picture>
```

Also, this should be done _only_ to images that are inside the selection/description part of the page, leaving other images on the page untouched. And it should happen _only_ on variable products.

And, the image should change as expected based on selection of variation :)

2021-07-12 15:36 UTC, piotrbak approved these changes
Looks like the problem is fixed, good to go!

[testrail-report-215.pdf](https://github.com/wp-media/imagify-plugin/files/6802613/testrail-report-215.pdf)

2021-07-13 13:38 UTC, merged