fix pricing table and cupon input
wp-media/imagify-plugin pull request #593
Opened 2021-07-09 15:21 UTC by mostafa-hisham

fix #557 and #556

2021-07-13 14:00 UTC, iCaspar requested changes
A couple very small things.

2021-07-13 14:00 UTC, iCaspar commented on assets/js/pricing-modal.js
> +		$('.imagify-pre-checkout-offers .imagify-offer-monthly .imagify-offer-content').html('');*/
Remove Commented-out code.

2021-07-13 14:00 UTC, iCaspar commented on assets/js/pricing-modal.js
> +								$('#imagify-coupon-code').val(promo_datas.label);
Type-o in variable name - appliesTo

2021-07-13 14:00 UTC, iCaspar commented on assets/js/pricing-modal.js
> +			if ( appliseTo.includes(datas[Object.keys(datas)[0]].label) ){
Type-o same as above -- appliesTo

2021-07-13 14:53 UTC, mostafa-hisham commented on assets/js/pricing-modal.js
> +		$('.imagify-pre-checkout-offers .imagify-offer-monthly .imagify-offer-content').html('');*/
done

2021-07-13 14:54 UTC, mostafa-hisham commented on assets/js/pricing-modal.js
> +			if ( appliseTo.includes(datas[Object.keys(datas)[0]].label) ){
i changed it to `applies_to`

2021-07-13 14:54 UTC, mostafa-hisham commented on assets/js/pricing-modal.js
> +								$('#imagify-coupon-code').val(promo_datas.label);
changed it to `applies_to`

2021-07-13 17:31 UTC, iCaspar approved these changes

2021-07-13 17:31 UTC, iCaspar commented
Ready for @wp-media/qa

2021-07-14 13:37 UTC, piotrbak commented
@mostafa-hisham When promo is set to all plans, the coupon is not applied at all, but the prices are crossed out:
![image](https://user-images.githubusercontent.com/26767037/125631284-ffb91470-fa99-4e48-88a4-0fcd44f1bf92.png)

The discount text is also not present at the end of the checkout process:
![image](https://user-images.githubusercontent.com/26767037/125631546-917790a2-bd28-452d-9be2-b46d3e08b044.png)

The 0 is crossed out:
![image](https://user-images.githubusercontent.com/26767037/125631417-e1fdbe1a-b0ce-4be5-80cc-7da89eff2b5d.png)
![image](https://user-images.githubusercontent.com/26767037/125631461-f34c98f8-789d-45bb-ab7b-6e6bdba14eb8.png)

2021-07-14 14:27 UTC, mostafa-hisham commented
@piotrbak 

> @mostafa-hisham When the promo is set to all plans, the coupon is not applied at all, but the prices are crossed out:
> ![image](https://user-images.githubusercontent.com/26767037/125631284-ffb91470-fa99-4e48-88a4-0fcd44f1bf92.png)
> 
**FIXED**

> The discount text is also not present at the end of the checkout process:
> ![image](https://user-images.githubusercontent.com/26767037/125631546-917790a2-bd28-452d-9be2-b46d3e08b044.png)
> 

this part is coming from "https://app.tst.imagify.io/#/plugin/0/0/15/wpr10/" in <iframe>
I think it is related to this issue https://github.com/wp-media/imagify/issues/1580

> The 0 is crossed out:
> ![image](https://user-images.githubusercontent.com/26767037/125631417-e1fdbe1a-b0ce-4be5-80cc-7da89eff2b5d.png)
> ![image](https://user-images.githubusercontent.com/26767037/125631461-f34c98f8-789d-45bb-ab7b-6e6bdba14eb8.png)
>
**FIXED**

2021-07-14 14:46 UTC, piotrbak commented
@mostafa-hisham Now it's possible to apply a promo coupon to the plan that's not in promotion. To reproduce:
1. Promo is set to have only unlimited in promotion
2. Go to checkout, choose Growth
3. Add the promo coupon (`spring`) and click ok
4. The coupon is applied
5. Go to checkout, the checkout is not possible because the coupon is not valid.

![image](https://user-images.githubusercontent.com/26767037/125642338-187a6caf-2888-4abb-a01a-6670fb2bba41.png)

2021-07-14 17:28 UTC, mostafa-hisham commented
@piotrbak 
please check if you can apply a promo coupon to the plan that's not in the promotion
after this change

2021-07-15 12:47 UTC, piotrbak approved these changes
Seems that we're fine there. The PR wasn't tested against a situation when there are two plans in the promo campaign. John wasn't able to set it up.
[testrail-report-218.pdf](https://github.com/wp-media/imagify-plugin/files/6823141/testrail-report-218.pdf)

2021-07-15 15:25 UTC, merged