Update requirements and version for 1.10
wp-media/imagify-plugin pull request #599
Opened 2021-07-13 16:51 UTC by iCaspar

Closes #597

- [X] Update minumum requirements to WP 5.6 / PHP 7.0
- [X] Remove `compat.php` and references to it.

2021-07-13 17:00 UTC, Tabrisrp requested changes
In `imagify.php`, it's also necessary to change the WP & PHP values to check in the instantiation of the Requirements check class on lines 116 & 117

2021-07-13 17:00 UTC, remyperona commented on readme.txt
> +Tested up to: 5.7.2
```suggestion
Tested up to: 5.8
```

2021-07-13 17:00 UTC, remyperona commented on readme.txt
> +Requires at least: 5.3
```suggestion
```
This header is not part of the list for the readme file in fact, we can remove it (see https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#example-readme)

2021-07-13 17:28 UTC, iCaspar commented
Updated -- tests are failing on the legacy WP part of the matrix now until I can get the [8.0 changes](https://github.com/wp-media/imagify-plugin/issues/559) in... will do that next 😄

2021-07-13 17:36 UTC, Tabrisrp approved these changes

2021-07-13 19:29 UTC, iCaspar commented
@wp-media/qa This is ready, but if you do #600 first, I can merge that one into here and get the last failing CI tests back to green on this one for you.

2021-07-14 10:42 UTC, piotrbak approved these changes
It's all good!

2021-07-15 15:12 UTC, merged