Closes 2554: Prevent having a webp bigger than the original
wp-media/imagify-plugin pull request #751
Opened 2023-10-24 13:29 UTC by CrochetFeve0251

## Description
Fixes #2554

Display the message when we display a original format instead of the webp one.

## Type of change

*Please delete options that are not relevant.*

- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

2023-10-25 13:36 UTC, Tabrisrp requested changes
I'm not understanding how the changes are preventing the WebP bigger than original?

Also, the referenced issue is not correct.

2023-10-25 13:36 UTC, Tabrisrp commented on inc/classes/class-imagify-files-list-table.php
> +					</li>
This list item is the same as the list item right above?

2023-10-25 13:59 UTC, CrochetFeve0251 commented on inc/classes/class-imagify-files-list-table.php
> +					</li>
The idea of this part is to give a message when the webp is not generated cause we keep the original with optimizations.

Also this PR is in two parts and the actual logic to prevent this is on the python part: https://github.com/wp-media/imagify/pull/2567

2023-10-26 13:44 UTC, Tabrisrp commented
We also have this PR related https://github.com/wp-media/imagify-plugin/pull/706

2023-10-26 13:45 UTC, Tabrisrp approved these changes

2023-11-08 07:52 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the update. Please find exploratory test notes below
1- The served image at the FE has size > the optimized size (for this image WebP isnot generated, however it's served, shouldn't we serve png in this case? even if the option to display WebP image on the website is enabled @wp-media/productimagify )
![Screenshot from 2023-11-08 09-23-55](https://github.com/wp-media/imagify-plugin/assets/76941962/817f8f33-a99c-41dc-b84a-1bbdc9ad0094)
![Screenshot from 2023-11-08 09-22-06](https://github.com/wp-media/imagify-plugin/assets/76941962/d92bc951-735a-4006-9092-b7f9bdf8f29a)
2- WebP generated is always no although it was generated (@wp-media/productimagify what shall be the text for convert when the image is converted to WebP? do we really need this field?)
![Screenshot from 2023-11-08 09-38-48](https://github.com/wp-media/imagify-plugin/assets/76941962/f14d1058-ce36-49d7-8e7f-c7db6ec9f993)

2023-11-09 14:13 UTC, Tabrisrp approved these changes

2023-11-09 15:47 UTC, MathieuLamiot commented
@Mai-Saad, thanks for the detailed report.
About the 2nd point: 
- If the WebP is generated (because it is smaller), then WebP Generated should be set to "Yes".
- If the WebP is not generated (because it is bigger, or for any other reasons actually), then WebP generated should be set to "No".
I think it should be fixed as part of this issue @CrochetFeve0251 

I do agree it seems a bit redundant with the message above saying WebP is not generated because it is bigger. It could be a small simplification, but let's see what @wp-media/productimagify thinks about this. We might not have all the cases in minds. In any case, that would be outside the scope of the issue..

2023-11-09 16:07 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the update. @MathieuLamiot Thanks for the feedback.
Currently:
- Specific image has no WebP generated while status is yes
![Screenshot from 2023-11-09 18-04-06](https://github.com/wp-media/imagify-plugin/assets/76941962/8d931906-a34f-411a-aa89-6cf5d23bb9e9)
- An image which isnot converted, is served with a bigger size (tested on chrome ubuntu) (note: this image wasnot compressed somehow)
![Screenshot from 2023-11-09 18-06-32](https://github.com/wp-media/imagify-plugin/assets/76941962/22c8bfd1-483a-406b-a5cd-009064a201ff)
![Screenshot from 2023-11-09 18-05-46](https://github.com/wp-media/imagify-plugin/assets/76941962/5e4e60b0-7ee6-4979-b164-d02c13ad5641)

2023-11-10 12:35 UTC, Mai-Saad commented
@CrochetFeve0251 Thanks for the update. Working as the following now. If agreed by @wp-media/productimagify then we can merge.

1. Original image is non webp

- If generated WebP is < original image => no convert msg, WebP generated status is yes and served on FE if the serve option is enabled
- If generated WebP is > original image => convert msg `Webp is less performant than original`, WebP generated status is either No (if no webp file added to upload folder) or partial (if the webP file added to upload folder), image.extension is served on FE (as same as that in upload folder without extension nor dimensions and it is <= original size) if the serve webP option on/off

2- Original image is webP

- no convert msg, WebP generated status is No, The optimized image is served (approximately as same as that in upload folder )

3- Already on trunk, origional/ optimized size is not matching that in the upload folder https://wp-media.slack.com/archives/CU0F6EGQ1/p1699598198861799

4- Already on trunk, while display image in webp isnot checked, the used size at FE is that of webp but without adding webp extension https://wp-media.slack.com/archives/CU0F6EGQ1/p1699618969452739

2023-11-13 11:13 UTC, DahmaniAdame commented
Looks good. The only change is on the wording to make it clearer about why the origin image will be served instead: 

Change: 

```Webp is less performant than original```

To:

```WebP file is larger than the original image```

2023-11-13 13:50 UTC, merged

2023-11-13 13:58 UTC, Mai-Saad commented
![Screenshot from 2023-11-13 15-58-06](https://github.com/wp-media/imagify-plugin/assets/76941962/8619a737-d4b5-497f-88dd-0ef95f374b1a)