Added a fix for the lightbox
wp-media/imagify-plugin pull request #762
Opened 2023-11-22 11:07 UTC by CrochetFeve0251

## Description

Added a fix for the lightbox by not passing the wp attributes to the picture tag.

Fixes #758

## Type of change

*Please delete options that are not relevant.*

- New feature (non-breaking change which adds functionality).
- Bug fix (non-breaking change which fixes an issue).
- Enhancement (non-breaking change which improves an existing functionality).
- Breaking change (fix or feature that would cause existing functionality to not work as before).
- This change requires a documentation update.

## Is the solution different from the one proposed during the grooming?

No.

# Checklists

## Generic development checklist

- [ ] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [ ] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

*If not, detail what you could not test.*

*Please describe any additional tests you performed.*

2023-11-22 14:13 UTC, Tabrisrp requested changes

2023-11-22 14:13 UTC, Tabrisrp commented on classes/Webp/Picture/Display.php
> +		$picture_attributes = array_filter( $attributes, function ( $attribute ) {
Could we do it in the build_attributes() method instead?

2023-11-22 14:51 UTC, CrochetFeve0251 commented on classes/Picture/Display.php
> +		$picture_attributes = array_filter( $attributes, function ( $attribute ) {
@Tabrisrp actually we can't cuase this method is also used for creating the attributes from the `img` tag on which we want to keep them.

2023-11-22 17:16 UTC, Tabrisrp approved these changes

2023-11-24 07:35 UTC, vmanthos commented
@CrochetFeve0251 Thank you for the PR.

The issue has been fixed but there is a console error that's not there with `trunk`:
```javascript
Uncaught TypeError: Cannot read properties of null (reading 'focus')
````
![image](https://github.com/wp-media/imagify-plugin/assets/193660/79860376-8087-4266-a13a-c4d1ba1ac292)

This can be seen here:
https://vasilis.rocketlabsqa.ovh/wordpress-6-4-lightbox-implementation

1. Click on the jellyfish picture.
2. Close the lightbox using the `x` button or the picture itself.
3. Check the console log.

Can you please check this? :pray:

2026-01-06 16:07 UTC, Mai-Saad commented
@remyperona Thanks for the update. 
is it expected to load both next-gen and normal image when click on the image? /cc @piotrbak 
<img width="1920" height="1080" alt="Screenshot from 2026-01-06 18-05-15" src="https://github.com/user-attachments/assets/85e56299-878e-47e3-a59c-3df63cf75493" />

2026-01-06 19:54 UTC, remyperona commented
It's not expected, but this WP feature is also not planned to work with picture element I think. I would say it's an acceptable side effect compared to the current issue.

2026-01-08 09:16 UTC, Mai-Saad commented
Items for exploratory 

- [x] same issue is working fine with avif
- [x] same issue is working fine with normal optimized image served as picture
- [x] serve webp image is still good on both apache and nginx
- [x] serve webp image as picture is good with WPR (with /without webp option at wpr) and lightbox is still good
- is there any other feature like lightbox to be explored?

2026-01-08 16:17 UTC, nicomollet approved these changes
It looks good but needs proper QA

2026-07-21 22:48 UTC, merged