Enhancement/764 add avif rewrite rules
wp-media/imagify-plugin pull request #774
Opened 2024-01-05 05:23 UTC by Miraeld

## Description

This PR adds the rewrite rules management for the AVIF picture format

Fixes #764 

## Type of change

- New feature (non-breaking change which adds functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2024-01-07 15:02 UTC, Tabrisrp requested changes
You can do the same changes in the Nginx file

2024-01-07 15:02 UTC, remyperona commented on classes/Avif/RewriteRules/Apache.php
> +defined( 'ABSPATH' ) || die( 'Cheatin’ uh?' );
You can remove this line, we don't need it in classes

2024-01-07 15:02 UTC, remyperona commented on classes/Avif/RewriteRules/Apache.php
> +class Apache extends \Imagify\WriteFile\AbstractApacheDirConfFile {
You can import the class (`use`) before using it here

2024-01-07 15:02 UTC, remyperona commented on classes/Avif/RewriteRules/Apache.php
> + * @author Gael Robin
You can remove the `@author` references, we don't use them anymore

2024-01-08 12:49 UTC, Miraeld commented on classes/Avif/RewriteRules/Apache.php
> +defined( 'ABSPATH' ) || die( 'Cheatin’ uh?' );
I've updated both classes :)

2024-01-08 12:49 UTC, Miraeld commented on classes/Avif/RewriteRules/Apache.php
> + * @author Gael Robin
I've updated both classes :)

2024-01-08 12:49 UTC, Miraeld commented on classes/Avif/RewriteRules/Apache.php
> +class Apache extends \Imagify\WriteFile\AbstractApacheDirConfFile {
I've updated both classes :)

2024-01-16 13:39 UTC, Khadreal approved these changes
Looks good to me :)

2024-01-16 16:56 UTC, Tabrisrp requested changes
This PR is missing the instantiation and loading of the init method of the class, but I want to move to the container + event manager instead, so we could do it once they are in

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		$new_value = ! empty( $values['display_avif_method'] ) ? $values['display_avif_method'] : '';
```suggestion
		$old_value = get_imagify_option( 'display_next_gen_method' );
		$new_value = ! empty( $values['display_next_gen_method'] ) ? $values['display_next_gen_method'] : '';
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		if ( ! get_imagify_option( 'display_avif' ) ) {
```suggestion
		if ( ! get_imagify_option( 'display_next_gen' ) ) {
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		if ( self::OPTION_VALUE !== get_imagify_option( 'display_avif_method' ) ) {
```suggestion
		if ( self::OPTION_VALUE !== get_imagify_option( 'display_next_gen_method' ) ) {
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		if ( ! get_imagify_option( 'display_avif' ) ) {
```suggestion
		if ( ! get_imagify_option( 'display_next_gen' ) ) {
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		if ( self::OPTION_VALUE !== get_imagify_option( 'display_avif_method' ) ) {
```suggestion
		if ( self::OPTION_VALUE !== get_imagify_option( 'display_next_gen_method' ) ) {
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		$was_enabled = (bool) get_imagify_option( 'display_avif' );
```suggestion
		$was_enabled = (bool) get_imagify_option( 'display_next_gen' );
```

2024-01-16 16:56 UTC, Tabrisrp commented on classes/Avif/RewriteRules/Display.php
> +		$is_enabled  = ! empty( $values['display_avif'] ) && ! empty( $values['convert_to_avif'] );
```suggestion
		$is_enabled  = ! empty( $values['display_next_gen'] ) && ! empty( $values['convert_to_avif'] );
```

2024-01-17 04:10 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		$is_enabled  = ! empty( $values['display_avif'] ) && ! empty( $values['convert_to_avif'] );
It's been changed

2024-01-17 04:10 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		$was_enabled = (bool) get_imagify_option( 'display_avif' );
It's been changed

2024-01-17 04:10 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		if ( self::OPTION_VALUE !== get_imagify_option( 'display_avif_method' ) ) {
It's been changed

2024-01-17 04:10 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		if ( ! get_imagify_option( 'display_avif' ) ) {
It's been changed

2024-01-17 04:11 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		if ( self::OPTION_VALUE !== get_imagify_option( 'display_avif_method' ) ) {
It's been changed

2024-01-17 04:11 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		if ( ! get_imagify_option( 'display_avif' ) ) {
It's been changed

2024-01-17 04:11 UTC, Miraeld commented on classes/Avif/RewriteRules/Display.php
> +		$new_value = ! empty( $values['display_avif_method'] ) ? $values['display_avif_method'] : '';
It's been changed

2024-01-18 21:54 UTC, merged