Add league/container, event-manager to composer and mozart
wp-media/imagify-plugin pull request #782
Opened 2024-01-16 15:22 UTC by Khadreal

## Description

Add league/container, event-manager to composer using mozart.

Fixes #776 

## Type of change
- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?
No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [ ] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

2024-01-16 17:00 UTC, Tabrisrp requested changes
The event manager import into the dependencies is missing currently

2024-01-16 20:57 UTC, Khadreal commented
> The event manager import into the dependencies is missing currently

Fixed

2024-01-17 14:37 UTC, Miraeld approved these changes

2024-01-18 21:52 UTC, Tabrisrp approved these changes

2024-01-18 21:53 UTC, merged