Closes #796: Auto generation of AVIF on save
wp-media/imagify-plugin pull request #806
Opened 2024-02-19 15:21 UTC by Miraeld

# Description

Fixes #796 

## Documentation

### User documentation

Fix the issue related to the auto-optimization on save while AVIF is being enable. 

### Technical documentation

When we save the Imagify settings, we get to a callback which will check if the AVIF is enable or not. 
If it is, we will start optimizing the images when AVIF is missing in order to generate these AVIF versions of images.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.

## Observability
- [x] I handled errors when needed.

2024-02-19 15:45 UTC, Tabrisrp commented
There is some conflicts to fix after the merge of my PR to the main branch

2024-02-20 09:39 UTC, jeawhanlee commented
@Miraeld Could you fix the codacy errors, they are mostly related to phpcs.

2024-02-20 21:59 UTC, Tabrisrp requested changes

2024-02-20 21:59 UTC, Tabrisrp commented on classes/Bulk/Bulk.php
> +	public function maybe_generate_avif_on_save($args = null) {
This isn't right. Some of the changes that I made in PR #797 have disappeared here.

Also this should use 2 parameters, `$old_value` and `$value`, and do a `return` only when bailing-out, not `imagify_die()`

2024-02-21 14:37 UTC, Miraeld commented on classes/Bulk/Bulk.php
> +	public function maybe_generate_avif_on_save($args = null) {
I've made some change back to use back the `bulk_optimization` on the save instead of the new methods I've introduced in my previous commits.

2024-02-21 20:32 UTC, Tabrisrp approved these changes

2024-02-22 14:08 UTC, Miraeld commented
As noted by @Mai-Saad , if we run only this branch, we might get our file deleted. 

However, merging this branch with [this one](https://github.com/wp-media/imagify-plugin/pull/807) fix the issue :) 

So this PR requires https://github.com/wp-media/imagify-plugin/pull/807 :)

2024-02-22 15:00 UTC, merged