Avif/media library#794
wp-media/imagify-plugin pull request #810
Opened 2024-02-21 11:56 UTC by Khadreal

# Description
Display the smaller size of the image(avif)

Fixes #794 

## Documentation

### User documentation

This will show the avif image size & percentage when available 

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
N/A

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I did not introduce unecessary complexity.

2024-02-21 15:03 UTC, Miraeld approved these changes

2024-02-21 20:27 UTC, Tabrisrp requested changes
I think we should go further on this one, updating this method and other methods in the class that reference webp, to make it work with the new implementation (using next-gen). This would also require to update the interface.

2024-02-21 21:43 UTC, Khadreal commented
> I think we should go further on this one, updating this method and other methods in the class that reference webp, to make it work with the new implementation (using next-gen). This would also require to update the interface.

If I understand correctly, we should update the method from webp to nextgen ?

2024-02-22 14:17 UTC, Tabrisrp commented
Yes, update all occurrences of webp to nextgen. I see there is also a use of `imagify_path_to_webp()` that should be updated in this class for example.

2024-02-23 13:36 UTC, Miraeld approved these changes

2024-02-26 20:54 UTC, Tabrisrp requested changes

2024-02-26 20:54 UTC, Tabrisrp commented on classes/Optimization/Data/AbstractData.php
> +		$format = '.webp';
```suggestion
		$format = 'webp';
```

2024-02-26 20:54 UTC, Tabrisrp commented on classes/Optimization/Data/AbstractData.php
> +				$format = '.avif';
```suggestion
				$format = 'avif';
```

2024-02-27 13:03 UTC, Mai-Saad commented
@Khadreal Thanks for the PR. please find exploratory note below:
- when upload image while avif is off, we arenot generating webP by default
- when enable avif after that, we arenot generating avif for uploaded images in previous step
can you please check? (those points were working on the main feature branch)

2024-02-28 09:23 UTC, Khadreal commented
> @Khadreal Thanks for the PR. please find exploratory note below:
> 
> * when upload image while avif is off, we arenot generating webP by default
> * when enable avif after that, we arenot generating avif for uploaded images in previous step
>   can you please check? (those points were working on the main feature branch)

The branch has been updated to the latest feature branch

2024-02-28 12:19 UTC, jeawhanlee approved these changes

2024-02-28 14:27 UTC, Tabrisrp approved these changes

2024-03-03 10:34 UTC, Mai-Saad commented
@Khadreal Thanks for the PR. working as in trunk after merging main branch to the PR locally.

Note: we have some discussion about sizes here (probably it isnot always the smallest on trunk), however, the agreed expected shall be in separate GH as it's the case on trunk.

2024-03-05 16:48 UTC, Tabrisrp approved these changes

2024-03-11 16:50 UTC, Tabrisrp requested changes

2024-03-11 16:50 UTC, Tabrisrp commented on classes/Bulk/Bulk.php
> +		if ( isset( $value['convert_to_avif'] ) && ! (bool) $value['convert_to_avif'] ) {
the old code is the correct one, not this one

2024-03-13 12:04 UTC, Khadreal commented
This PR https://github.com/wp-media/imagify-plugin/pull/851 once merge will fixed the failing test error

2024-03-14 09:28 UTC, MathieuLamiot commented
@Khadreal should this go back to ready for review, or there are still work needed here?

2024-03-14 10:35 UTC, Khadreal commented
> @Khadreal should this go back to ready for review, or there are still work needed here?

I'll move it, done with the work but didn't move it because of the test failing

2024-03-14 12:37 UTC, Mai-Saad commented
@Khadreal Thanks for the update. Please find exploratory note below:
- Can see the following error for medium size image 
`[14-Mar-2024 12:29:32 UTC] PHP Warning:  Undefined array key "optimized_size" in /home/mai/Local Sites/imagifynginx6/app/public/wp-content/plugins/imagify-plugin/classes/Optimization/Data/AbstractData.php on line 309`
in the following scenario:
1- install and activate imagify
2- upload med size image attached
![marchmed1](https://github.com/wp-media/imagify-plugin/assets/76941962/b1d2d02f-a7a1-45fe-9392-fbeb5ceeda0e)
3- enable avif 

or 
1- activate avif 
2- upload the same image

![Screenshot from 2024-03-14 14-24-53](https://github.com/wp-media/imagify-plugin/assets/76941962/bfe32a49-c355-4210-9e14-46009a69f669)


can you please check?

2024-03-15 14:34 UTC, Khadreal commented
Got this error, wondering if you're seeing something like this as well. This is when avif is not enable.

<img width="1311" alt="Screenshot 2024-03-15 at 15 33 51" src="https://github.com/wp-media/imagify-plugin/assets/10527515/ec01859e-cba2-40c0-9878-7d6d9553bef9">

2024-03-15 16:02 UTC, Khadreal commented
> #794



> Got this error, wondering if you're seeing something like this as well. This is when avif is not enable.
> 
> <img alt="Screenshot 2024-03-15 at 15 33 51" width="1311" src="https://private-user-images.githubusercontent.com/10527515/313229050-ec01859e-cba2-40c0-9878-7d6d9553bef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTg2MDksIm5iZiI6MTcxMDUxODMwOSwicGF0aCI6Ii8xMDUyNzUxNS8zMTMyMjkwNTAtZWMwMTg1OWUtY2JhMi00MGMwLTk4NzgtN2Q2ZDk1NTNiZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE1NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZDgyMGIxNDAxNzc0ODA3NjQzZjMwMDVmOTIyMTI3YzQ0MDczYzc1ZjJlMTFmYWY5NGQ5YjE2MDE2YmQyOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1U9XiKYjnw3TocZumjOgVEKwI9zmPrpCp5YnV70T5U">

My last update fixed this too

2024-03-15 19:44 UTC, Tabrisrp approved these changes

2024-03-18 10:14 UTC, Mai-Saad commented
@Khadreal Thanks for the update, fixed in both scenarios mentioned above but can see problem if we refresh admin after scenario 2 i.e
1- install and activate imagify
2- enable avif
3- upload the image => avif created and no error
4- refresh media page , the warning is there

in log can see
`[18-Mar-2024 09:52:12 UTC] PHP Warning:  Undefined array key "full@imagify-webp" in /home/mai/Local Sites/imagifynginx6/app/public/wp-content/plugins/imagify-plugin/classes/Optimization/Data/AbstractData.php on line 314`

note: it happens with any optimized image not just the previous one
[screen-capture (88).webm](https://github.com/wp-media/imagify-plugin/assets/76941962/9fb5f647-d695-4d0c-ac29-6a2232d79ed5)

2024-03-18 12:25 UTC, Khadreal commented
Fixed. please check again. 
Sorry for the back and forth

2024-03-20 08:27 UTC, Mai-Saad commented
@Khadreal Thanks for the update. Working fine now with the following note (which is fine as per https://wp-media.slack.com/archives/CU0F6EGQ1/p1709546156479809?thread_ts=1709458320.636499&cid=CU0F6EGQ1)
- if we manually deleted next-gen, the displayed size won't change even after refresh media page (i.e displayed size is that of avif, then manually delete the avif, the displayed size still is that of avif)

2024-03-20 08:56 UTC, merged