Apply nginx rules for next gen images
wp-media/imagify-plugin pull request #824
Opened 2024-02-27 16:49 UTC by wordpressfan

# Description

Fixes #821

## Documentation

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
*Delete options that are not relevant.*

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [ ] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [ ] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [ ] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

2024-02-28 12:18 UTC, jeawhanlee commented on classes/Webp/RewriteRules/Nginx.php
Shouldn't we update the value of the class const `TAG_NAME` to be generic?
Don't we also need to move it out of the Webp namespace?

2024-02-28 12:18 UTC, jeawhanlee commented on classes/Avif/RewriteRules/Nginx.php
Should we still keep this class?

2024-02-28 14:26 UTC, remyperona requested changes

2024-02-28 14:26 UTC, remyperona commented on inc/functions/attachments.php
> +			'avif'         => 'image/avif',
this should not be added, it's causing bugs in some cases (we already reverted it in a previous PR)

2024-02-28 14:26 UTC, remyperona commented on classes/Webp/RewriteRules/Nginx.php
I agree it feels weird to do it like this

2024-02-29 06:04 UTC, wordpressfan commented on classes/Webp/RewriteRules/Nginx.php
I mentioned that in the PR description (risks part) but let me explain this in details, the idea here is, currently our customers have old webp rules and if I understand this part well, we are detecting those rules by this tag name, so if I changed this tag name without adding an update routine to completely remove the old rules, we will end up having two rules, something like the following:

```
# BEGIN Imagify: rewrite rules for webp
OLD RULES
# END Imagify: rewrite rules for webp

# BEGIN Imagify: rewrite rules for nextgen
NEW RULES
# END Imagify: rewrite rules for nextgen
```

but if we kept it as webp we will not need this update routine.

If u think that would be confusing/weird we can have this update routine.

2024-02-29 06:06 UTC, wordpressfan commented on classes/Avif/RewriteRules/Nginx.php
I already mentioned this also in the PR description :D 
to keep the structure consistent, I kept it.
But let's think about this together.

2024-02-29 06:06 UTC, wordpressfan commented on inc/functions/attachments.php
> +			'avif'         => 'image/avif',
Many thanks, going to remove it then, wasn't aware of this previous PR.

2024-02-29 14:07 UTC, Tabrisrp approved these changes

2024-03-01 09:50 UTC, Mai-Saad commented
Rules applied correctly on apache, local and imagify.rocketlabs.

Note: on https://imagify.rocketlabsqa.ovh/ if we uploaded the zip file of any plugin, we will have error in media library (may needs further investigations when documenting changes needed at nginx server) => without playing with nginx rules at newer.rocketlabsqs upload plugin zip is fine

2024-03-01 11:57 UTC, merged