Closes #2886: Replace the existing "What Plan Do I Need" banner with the new one
wp-media/imagify-plugin pull request #904
Opened 2024-10-03 16:16 UTC by jeawhanlee

# Description

Fixes https://github.com/wp-media/imagify/issues/2886
Users now see all plans on the upgrade modal at first glance.

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario

No Issue to reproduce

## Technical description

### Documentation

- Updated plans modal and the plan switcher

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I did not introduce unnecessary complexity.

2024-10-03 16:30 UTC, jeawhanlee commented
New Modal Design:
![Screenshot 2024-10-03 at 17 27 39](https://github.com/user-attachments/assets/845bc544-2d1f-4a38-856f-1191d82b117d)

Old Modal Design:
![Screenshot 2024-10-03 at 17 28 59](https://github.com/user-attachments/assets/a9f426db-329b-4691-9e55-1902c3034258)
![Screenshot 2024-10-03 at 17 29 14](https://github.com/user-attachments/assets/413c3f40-600d-4efa-a530-eb009196cfb9)

2024-10-03 17:58 UTC, Tabrisrp requested changes

2024-10-03 17:58 UTC, Tabrisrp commented on assets/css/pricing-modal.css
> +/** End Toggle Switch **/
I would suggest to prefix all those classes with `imagify-` to make sure it doesn't conflict with anything else, the names are too generic currently

2024-10-03 17:58 UTC, Tabrisrp commented on assets/js/pricing-modal.js
> +
prefix to be reflected here

2024-10-04 13:36 UTC, Tabrisrp approved these changes

2024-10-07 08:56 UTC, Mai-Saad commented
NewBanner free:
![newbanner_free](https://github.com/user-attachments/assets/2b8c0040-29f6-4e2c-b472-6a46ee23d740)

New popup:
![newPopUp_2](https://github.com/user-attachments/assets/10510b88-ec59-4893-a377-683355145849)
![newPopup_1](https://github.com/user-attachments/assets/c9dffe96-4e1b-4f51-9e64-c7ea46fc31e3)

No green banner for growth and infinite user :heavy_check_mark:

2024-10-07 10:38 UTC, marija-nikolic commented
Hi team, please make sure that we are using the arrow from Font Awesome 6 pro on the buttons. I've just double-checked what Célia (our designer) is using. 

Please check the pink upgrade banners too.

2024-10-08 13:04 UTC, jeawhanlee commented
Both banners now having the expected arrow icon in button.

![Screenshot 2024-10-08 at 14 01 47](https://github.com/user-attachments/assets/536cf806-4ba0-4b26-a3de-08785b2f2664)

![Screenshot 2024-10-08 at 14 02 51](https://github.com/user-attachments/assets/8a7d5591-1a1c-4d63-ba57-03312d61e900)

2024-10-08 13:39 UTC, Tabrisrp approved these changes

2024-10-10 07:34 UTC, marija-nikolic commented
> Both banners now having the expected arrow icon in button.
> 
> ![Screenshot 2024-10-08 at 14 01 47](https://private-user-images.githubusercontent.com/38788055/374567189-536cf806-4ba0-4b26-a3de-08785b2f2664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDU2MzMsIm5iZiI6MTcyODU0NTMzMywicGF0aCI6Ii8zODc4ODA1NS8zNzQ1NjcxODktNTM2Y2Y4MDYtNGJhMC00YjI2LWEzZGUtMDg3ODViMmYyNjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjM2NjNWEzMzk0NjkxZTg0Y2RlZWI1MGQ3MzcwYzgzNjVjNjlhOWI0NmVkNDcxOTRhZmNjNTY4YTdiZTkxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EC9MmKDrvxTzCwjg7KrsTGlyVr4xacNq2dOs_BWTMqM)
> 
> ![Screenshot 2024-10-08 at 14 02 51](https://private-user-images.githubusercontent.com/38788055/374567529-8a7d5591-1a1c-4d63-ba57-03312d61e900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDU2MzMsIm5iZiI6MTcyODU0NTMzMywicGF0aCI6Ii8zODc4ODA1NS8zNzQ1Njc1MjktOGE3ZDU1OTEtMWExYy00ZDYzLWJhNTctMDMzMTJkNjFlOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ODkzNjEyZTQyMDQzMjk3YWU4ODg5ZjNiNGI3NWIwYWU0ZGU5YjRiNTkzODIzNTNiODQ5OTc4NTliYjE5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OPbOcc-fvoV9fSaOwlN2YQMHrdrSRQxRNX6USPbmX3s)

I am sorry @jeawhanlee, I missed this comment. The design of the pink banner is strange, it doesn't reflect what we should have. Could you please check? We validated everything with @Mai-Saad on the retreat.

2024-10-10 09:38 UTC, marija-nikolic commented
> NewBanner free: ![newbanner_free](https://private-user-images.githubusercontent.com/76941962/374100474-2b8c0040-29f6-4e2c-b472-6a46ee23d740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDU2MzMsIm5iZiI6MTcyODU0NTMzMywicGF0aCI6Ii83Njk0MTk2Mi8zNzQxMDA0NzQtMmI4YzAwNDAtMjlmNi00ZTJjLWI0NzItNmE0NmVlMjNkNzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZmI0MWE0ZTk3NWI3Yjc5MWM2NGM3MTc4MDJmNGViM2Y1OWU5N2FjZGVhODAwMDU1ZDg0NWRkNjljZDY1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oONy3_0hSPCGkBFZ1yq85mQ9xPV4zcQaOihgAchnenw)
> 
> New popup: ![newPopUp_2](https://private-user-images.githubusercontent.com/76941962/374100625-10510b88-ec59-4893-a377-683355145849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDU2MzMsIm5iZiI6MTcyODU0NTMzMywicGF0aCI6Ii83Njk0MTk2Mi8zNzQxMDA2MjUtMTA1MTBiODgtZWM1OS00ODkzLWEzNzctNjgzMzU1MTQ1ODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZWM1ODc2YTU2MmQ2OWU1NjE0YTUxMTJlMjA2OGI5MmY4ZDExOGY3OTUxY2Q5MjIyZGRiNGFjOTE3MDFiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r1hI4_3GLt0oqBAjcGW6Ay-01J1Muzct1WEO08TJfGA) ![newPopup_1](https://private-user-images.githubusercontent.com/76941962/374100631-c9dffe96-4e1b-4f51-9e64-c7ea46fc31e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDU2MzMsIm5iZiI6MTcyODU0NTMzMywicGF0aCI6Ii83Njk0MTk2Mi8zNzQxMDA2MzEtYzlkZmZlOTYtNGUxYi00ZjUxLTllNjQtYzdlYTQ2ZmMzMWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA3Mjg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNjM3NWM3MmM3MGVhMTZmMDliNWYyMzhkMGRiMTdkMGFhYjE3NTUwODJiODgzNDJhNmQzNDI5YTEwYjJjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ysbrCjeAFyVNtCGKd_ZVHjniBelaP82szeGadDhT_NY)
> 
> No green banner for growth and infinite user ✔️

Sorry for the delay in checking the new popups. In the end we won't have any changes, the only thing we should improve is the alignment of /MONTH:
You can use the alignment on https://app.imagify.io/subscription/ as a reference:
<img width="83" alt="image" src="https://github.com/user-attachments/assets/1af186d7-31d5-4f91-9609-0259b7921692">

2024-10-10 11:18 UTC, Mai-Saad commented
GreenBanner
![greenBanner](https://github.com/user-attachments/assets/59480e38-0e66-4034-8548-7ba4b68a6450)
PinkBanner
![pinkBanner](https://github.com/user-attachments/assets/34a86b68-3ea7-4fee-ba0b-b90fdbd200b3)
Adminbar when pinkBanner state
![redadminbar_noImagifyPage](https://github.com/user-attachments/assets/0478b93e-12a5-4d1f-8705-0783985e8234)

2024-10-15 07:26 UTC, Mai-Saad commented
> Adminbar when pinkBanner state (same already on production)
This is fixed now on PR
![AdminWIthremianing 20%](https://github.com/user-attachments/assets/7dba6666-d0e6-4e0f-91c5-014031e83cfa)

2024-10-15 07:51 UTC, Mai-Saad commented
Merged dev to the PR local and here are screenshots of banners
**Green banner** 
Settings page
![Screenshot from 2024-10-15 10-06-50](https://github.com/user-attachments/assets/60aaa9be-6f50-4bb0-9e8e-43565fddb4c0)

Bulk page
![BulkPageRemaining 20%](https://github.com/user-attachments/assets/d9030293-31f5-40ea-8616-2b535838f46e)



**Pink banner**
settings page 
![settingsRemaining20%](https://github.com/user-attachments/assets/a068b939-3d35-4500-bbe0-33278879b34f)

bulk page
![Screenshot from 2024-10-15 10-40-37](https://github.com/user-attachments/assets/2b2603ed-0f68-4dbf-a058-434513e1eff1)

**Click upgrade now popUp**
From admin bar link
![Screenshot from 2024-10-15 10-43-06](https://github.com/user-attachments/assets/d320d1d6-2aa4-4ff5-bba2-e76ec8eefc26)
![Screenshot from 2024-10-15 10-45-38](https://github.com/user-attachments/assets/22fd337d-8288-4a73-b99b-0445b88f78b8)

From green banner it keeps loading (@jeawhanlee can you please check this :pray:)

![upgrade_nowIn BulkPage](https://github.com/user-attachments/assets/325de66b-d237-4cdc-af95-921db7a62760)

2024-10-16 13:25 UTC, Mai-Saad commented
upgrade link from the green banner is working now
![Screenshot from 2024-10-16 16-03-09](https://github.com/user-attachments/assets/99dbebb6-556c-405d-9744-6af814f45206)
![Screenshot from 2024-10-16 16-03-16](https://github.com/user-attachments/assets/6f28dc75-e7f8-4b9d-bb4d-db08c4bd1ba1)

However, can see this in debug.log when click upgrade btn in admin bar after fresh install `[16-Oct-2024 13:09:36 UTC] PHP Deprecated:  round(): Passing null to parameter #1 ($num) of type int|float is deprecated in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-plugin/inc/classes/class-imagify-files-stats.php on line 408` ===> added new GH about that as it's already on trunk https://github.com/wp-media/imagify-plugin/issues/909

2024-10-17 14:28 UTC, merged